function NASTD_MEG_ERF_SelectTrials...
    (i_tonedur, param, paths_NASTD_MEG)
%Cut out trials per subject for specific TD, read out trial indices for
%specific subconditions, and provide a file ID for identification.
path_output = [paths_NASTD_MEG.Current_outputdata 'Data/Ssub/' param.tonedur_text{i_tonedur} 'sTD/'];
mkdir(path_output)

for i_sub = 1:length(param.subs)
    
    MEGactivity_perTrial = ...
        NASTD_MEG_ERF_DefineTrialsperTD(...
        param.subs{i_sub}, ...
        param.tonedur_text{i_tonedur}, ...
        param.samplefreq, ...
        paths_NASTD_MEG);
    
    %Output: Struct with cleaned MEG data for all trials for specific TD, including stim/trial info
    MEGactivity_perTrial.trialindices.predp34_low = ...
    find(MEGactivity_perTrial.stim.predID == -1); %p*34 = low
    MEGactivity_perTrial.trialindices.predp34_high = ...
    find(MEGactivity_perTrial.stim.predID == 1); %p*34 = high
      
    data_length_sec = length(MEGactivity_perTrial.trial{1})/param.samplefreq;
    MEGactivity_perTrial.ID = ...
        [param.subs{i_sub} '_' ...
        param.tonedur_text{i_tonedur} 'sTD_' ...
        num2str(data_length_sec) 'sDataLength'];
    
    %Save single-trial ERFs
    savefile = [path_output  param.subs{i_sub} '_MEGsingletrials_' ...
        param.tonedur_text{i_tonedur} 'sTD.mat'];
    save(savefile, 'MEGactivity_perTrial', '-v7.3');
    
    clear ERF_avgTrialsperCond MEGactivity_perTrial
    
end

end